### ISSUE TITLE
Intrinsics for serializer() function

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#1348]
Currently, our format API can be used in two ways: with explicit serializer, and with inferred from the type parameters, for exaple:
```
// Explicit
val jsonString = Json.decodeToString(MyClass.serializer(), MyClass(...))
val data = Json.encodeFromString(MyClass.serializer(), jsonString)

// Implicit
val jsonString = Json.decodeToString(MyClass(...)) // Inferred type-parameter T
val data = Json.encodeFromString<MyClass>(jsonString) // Or data: MyClass = Json.encodeFromString(sonString)
```

We always promote usages of the latter, because it has the same meaning, but in the meantime is more expressive and concise. It is based on the experimental `typeOf` function and we are able to retrieve the serializer using `KType`.

Unfortunately, it has two downsides:

- To retrieve the serializer, we have to use reflection. It prevents usage of this API with Graal (https://github.com/Kotlin/kotlinx.serialization/issues/1125) and also complicates Android usages
- Serializer retrieval is slow and often [slower than the serialization itself](https://www.reddit.com/r/Kotlin/comments/kd3wce/kotlin_json_performance_libraries/). The recommended and concise API shouldn't behave this way.

### Proposal

Introduce the notion of intrinsic to the serialization plugin. `serializer()` and `serializerOfNull` are going to be evaluated in the compile-time. Additionally, this evaluation will happen transitively through all `reified inline` functions that leverage `serializer<T>`.

To properly resolve context-specific serializers, more compact `contextualOrDefault(defaultSerializer)` function will be used instead.

**Comment by sandwwraith** [comment]
@NorbertSandor We can't give any particular timeframe for now, but we aim to provide this before Kotlin 1.6

**Comment by sdeleuze** [comment]
If possible we would live to get it in Kotlin 1.7 for Spring needs, especially related to GraalVM native images.

**Comment by snowe2010** [comment]
seems like this has been bumped several times. What work needs to be done here? Is there anything the community can do to help out?

**Comment by sandwwraith** [comment]
@snowe2010 The work has to be done in the compiler plugin — currently, they can't provide intrinsics, and we have to change that. I'm working at this task at the moment, and I hope I will be able to present results soon

**Comment by snowe2010** [comment]
@sandwwraith ah, I see. thank you for your work! good luck!

**Comment by PedroAlvarado** [comment]
It's been some time since the last update on this issue. Is it fair to expect this fixed some time next year?

**Comment by qwwdfsad** [comment]
It's already implemented in the not-yet-released Kotlin 1.8.0, stay tuned!

**Comment by sdeleuze** [comment]
Is it expected to be fixed with `kotlinx.serialization` 1.4.1 and Kotlin 1.8.0?

**Comment by sandwwraith** [comment]
As there are some runtime functions this functionality depends on, they should be working once 1.5.0-RC is released

**Comment by sandwwraith** [comment]
@morki Which function do you use? 1.8.0, which is used to compile 1.5.0-RC, has some subtle bug, and as a result, the `Json.encodeToString` function is not intrinsified. `serializer<T>()`, however, still should work with 1.8.x + 1.5.0-RC.

**Comment by snowe2010** [comment]
Hm. I was seeing the issue still as well, but I think it's because we're using the encode and decode methods.

**Comment by sandwwraith** [comment]
This feature is fully functional now. Requirements are Kotlin 1.8.10+ and serialization core runtime 1.5.0+.

**Comment by sandwwraith** [comment]
In an unlikely occasion of problems with replacement, inlining can be disabled with `freeCompilerArgs += ["-P", "plugin:org.jetbrains.kotlinx.serialization:disableIntrinsic=true"]`.

**Comment by OliverO2** [comment]
Ran a series of tests with `ProtoBuf` on JVM and Js. Works like a charm!
