### ISSUE TITLE
Sealed class with a generic type parameter crash on serialization

### ISSUE THREAD

**Issue by arkivanov** [Kotlin/kotlinx.serialization#3056]
**Code**

```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.json.Json

@Serializable
sealed interface State<out T> {
    @Serializable
    data object Loading : State<Nothing>

    @Serializable
    data class Data<out T>(val value: T) : State<T>
}

fun test(state: State<String>) {
    val json = Json.encodeToString(State.serializer(String.serializer()), state)
}
```

**Actual behavior**

Code compiles, there are no errors or warnings in the IDE, but crashes at runtime.

```
kotlinx.serialization.SerializationException: Serializer for subclass 'String' is not found in the polymorphic scope of 'Any'.
                 Check if class with serial name 'String' exists and serializer is registered in a corresponding SerializersModule.
                 To be registered automatically, class 'String' has to be '@Serializable', and the base class 'Any' has to be sealed and '@Serializable'.
                 	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
                 	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:114)
                 	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:109)
                 	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:250)
                 	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
                 	at com.test.State$Data.write$Self$_app_foo(Foo.kt:12)
                 	at com.test.State$Data$$serializer.serialize(Foo.kt:12)
                 	at com.test.State$Data$$serializer.serialize(Foo.kt:12)
                 	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:257)
                 	at kotlinx.serialization.json.internal.JsonStreamsKt.encodeByWriter(JsonStreams.kt:99)
                 	at kotlinx.serialization.json.Json.encodeToString(Json.kt:125)
                 	at com.test.FooKt.test(Foo.kt:17)
                 	...
```

**Expected behavior**

Either no crash or a compile error.

**Environment**
 - Kotlin version: 2.1.21
 - Library version: 1.7.3
 - Kotlin platforms: Android
 - Gradle version: 8.9
 - IDE version: Build #IC-251.23774.435, built on April 14, 2025

**Comment by sandwwraith** [comment]
Can you check Kotlin 2.2+ please? IIRC it was fixed

**Comment by sandwwraith** [comment]
Works in 2.2 for me, likely a duplicate of 2953

**Comment by PMARZV** [comment]
@sandwwraith i can still reproduce it with Kotlin 2.2.20 and the default template Compose project from Idea 
```kotlin
@Serializable
@SerialName("App")
sealed interface App {

    @Serializable
    @SerialName("Value")
    data class Value<T>(val value: T) : App

}
val app: App = App.Value(0f)
Json.encodeToString(app).also { println(it) }
```
fails with
```kotlin
Exception in thread "AWT-EventQueue-0" kotlinx.serialization.SerializationException: Serializer for subclass 'Float' is not found in the polymorphic scope of 'Any'.
Check if class with serial name 'Float' exists and serializer is registered in a corresponding SerializersModule.
To be registered automatically, class 'Float' has to be '@Serializable', and the base class 'Any' has to be sealed and '@Serializable'.
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:114)
	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:109)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:250)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
``` 
**In upload.jetbrains.com**: Upload id: 2025_09_28_G3H8EQcGDCDgdTZoJ6zria (file: composeAppReproSerialization.zip)
[Youtrack Issue](https://youtrack.jetbrains.com/issue/KT-81314/Sealed-class-with-a-generic-type-parameter-crash-on-serialization-Not-fixed-in-2.2.)
